return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "I can't do it while it's looking at me that way!",
			GENERIC = "Not shaveable.",
			NOBITS = "Poor thing is already bald as it is!",
		},
		STORE =
		{
			GENERIC = "At max capacity.",
			NOTALLOWED = "The item does not belong.",
		},
	},
	ACTIONFAIL_GENERIC = "I'm unable to comply.",
	ANNOUNCE_ADVENTUREFAIL = "Failure is eminent. Oh well, time to try again!",
	ANNOUNCE_BEES = "Bzzz!!",
	ANNOUNCE_BOOMERANG = "Ouch! How did I not catch that?!",
	ANNOUNCE_CHARLIE = "Wha-what was that?!",
	ANNOUNCE_CHARLIE_ATTACK = "Ouch! Something nipped me!",
	ANNOUNCE_COLD = "Brr..chilly!",
	ANNOUNCE_HOT = "Gah! Need..Shade...Or some..ice.",
	ANNOUNCE_CRAFTING_FAIL = "Hmm.. missing something.",
	ANNOUNCE_DEERCLOPS = "Monster?!",
	ANNOUNCE_DUSK = "Nights approaching..The shadows are coming.",
	ANNOUNCE_EAT =
	{
		GENERIC = "Delicious!",
		PAINFUL = " I feel queasy..",
		SPOILED = "Yuck! That was revolting!",
		STALE = "Well, That wasn't fresh.",
		INVALID = "I'm not eating that!",
	},
	ANNOUNCE_ENTER_DARK = "Ahh! I'm blind!",
	ANNOUNCE_ENTER_LIGHT = "Phew! My vision came back.",
	ANNOUNCE_FREEDOM = "I'm.. I'm free?! I'm Free!",
	ANNOUNCE_HIGHRESEARCH = "Nothing my genius couldn't handle.",
	ANNOUNCE_HOUNDS = "Do I hear barking?",
	ANNOUNCE_HUNGRY = "I'm starving!",
	ANNOUNCE_HUNT_BEAST_NEARBY = "Fresh tracks, The beast must be close.",
	ANNOUNCE_HUNT_LOST_TRAIL = "Darn! It ends here.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "The ground is too wet for footprints.",
	ANNOUNCE_INV_FULL = "My pockets are full!",
	ANNOUNCE_KNOCKEDOUT = "Err, My head is pounding!",
	ANNOUNCE_LOWRESEARCH = "It was bellow me.",
	ANNOUNCE_MOSQUITOS = "Ew, away with you!",
	ANNOUNCE_NODANGERSLEEP = "Your kidding me?! Things are out to get me!",
	ANNOUNCE_NODAYSLEEP = "The day is for adventuring!",
	ANNOUNCE_NODAYSLEEP_CAVE = "I don't feel like sleeping yet.",
	ANNOUNCE_NOHUNGERSLEEP = "I can't sleep on an empty stomach!",
	ANNOUNCE_NOSLEEPONFIRE = "Well, I will be well roasted.",
	ANNOUNCE_NODANGERSIESTA = "To many creatures watching me sleep!",
	ANNOUNCE_NONIGHTSIESTA = "I'd rather sleep then nap.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "The cave is too dangerous to relax in.",
	ANNOUNCE_NOHUNGERSIESTA = "My hunger won't allow it!",
	ANNOUNCE_NO_TRAP = "Pleasantly simple.",
	ANNOUNCE_PECKED = "Ow! Stop it!",
	ANNOUNCE_QUAKE = "Uh oh. The ceiling is falling.",
	ANNOUNCE_RESEARCH = "There's always something new!",
	ANNOUNCE_SHELTER = "Yes! Nature is on my side.",
	ANNOUNCE_THORNS = "Ow!",
	ANNOUNCE_BURNT = "Yikes! That burned!",
	ANNOUNCE_TORCH_OUT = "I should have invented something better.",
	ANNOUNCE_TRAP_WENT_OFF = "Oops.",
	ANNOUNCE_UNIMPLEMENTED = "Ouch. Not in completion.",
	ANNOUNCE_WORMHOLE = "Discovery comes at a price.",
	ANNOUNCE_CANFIX = "\n Nothing an inventor can not handle!",
	ANNOUNCE_ACCOMPLISHMENT = "A reward for my work!",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "Wilson will be so envious...",	
	ANNOUNCE_INSUFFICIENTFERTILIZER = "Not enough for you, eh?",
	ANNOUNCE_TOOL_SLIP = "Whoops!",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "That was beautiful!",

	ANNOUNCE_DAMP = "Great, I'm soggy.",
	ANNOUNCE_WET = "It seems now I'm fully drenched.",
	ANNOUNCE_WETTER = "I miraculously turned into a sponge!",
	ANNOUNCE_SOAKED = "I'm getting really wet and cold.",
	
	BATTLECRY =
	{
		GENERIC = "It's either you or me!",
		PIG = "Your hide is mine!",
		PREY = "Come now dinner!",
		SPIDER = "Spiders are meant to be squashed!",
		SPIDER_WARRIOR = "We will see who wins!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "I, uh, scared it off!",
		PIG = "I guess he has other uses.",
		PREY = "It got away!",
		SPIDER = "Wasn't worth my time.",
		SPIDER_WARRIOR = "Leave me alone, vile thing!",
	},
	DESCRIBE =
	{
        GLOMMER = "It's...It's adorable!",
        GLOMMERFLOWER = 
        {
        	GENERIC = "The petals capture the light.",
        	DEAD = "Even though it's dead it shines.",
        },
        GLOMMERWINGS = "I shall craft something with them and fly away!",
        GLOMMERFUEL = "It's pink and smells odd.",
        BELL = "Soothing to hear.",
        STATUEGLOMMER = 
        {	
        	GENERIC = "Mythical beast?",
        	EMPTY = "For the sake of curiosity.",
    	},

		WEBBERSKULL = "An odd looking skull. I suppose I can dig it up.",
		WORMLIGHT = "Looks good to eat.",
		WORM =
		{
		    PLANT = "Nothing bad should happen.",
		    DIRT = "A pile.. of dirt.",
		    WORM = "A worm with teeth!",
		},
		MOLE =
		{
			HELD = "Out of your element. Just like me.",
			UNDERGROUND = "A earthen creature looking for food.",
			ABOVEGROUND = "The way it sticks it head out..like a game.",
		},
		MOLEHILL = " A hole, I wonder what lives there!",
		MOLEHAT = "I hope the smell is worth it.",

		EEL = "Your sacrifice is not in vain.",
		EEL_COOKED = "Ready to eat!",
		UNAGI = "Prepared by a master!",
		EYETURRET = "My greatest invention!",
		EYETURRET_ITEM = "Holding back.. urge.. to poke.",
		MINOTAURHORN = "Pointy and deadly. I like it!",
		MINOTAURCHEST = "Contains either treasure or something much worse.",
		THULECITE_PIECES = "Bits of Thulecite.",
		POND_ALGAE = "Algae, nothing to it.",
		GREENSTAFF = "It contradicts me.",
		POTTEDFERN = "Decorative.",

		THULECITE = "Has it been always here?",
		ARMORRUINS = "It's weight dazzles me.",
		RUINS_BAT = "Heavy but deadly.",
		RUINSHAT = "Hahaha! It was made for me!!",
		NIGHTMARE_TIMEPIECE =
		{
		CALM = "Nothing happening. Great!",
		WARN = "Um. Something is going on.",
		WAXING = "It's becoming more alarmed!",
		STEADY = "It is steady.",
		WANING = "It's going away.",
		DAWN = "Finally, The nightmare is over!",
		NOMAGIC = "No magic at all.",
		},
		BISHOP_NIGHTMARE = "Its in a terrible state!",
		ROOK_NIGHTMARE = "Broken beyond repair!",
		KNIGHT_NIGHTMARE = "Its a knight something!",
		MINOTAUR = "I think its glaring at me.",
		SPIDER_DROPPER = "I hear it but don't want to see it.",
		NIGHTMARELIGHT = "Its purpose must be discovered!",
		NIGHTSTICK = "Electricity!",
		GREENGEM = "I like the color!",
		RELIC = "Ancient relics with history.",
		RUINS_RUBBLE = "It's in my nature to fix it.",
		MULTITOOL_AXE_PICKAXE = "An inventors dream tool!",
		ORANGESTAFF = "It makes walking irrational.",
		YELLOWAMULET = "A kiss from the sun.",
		GREENAMULET = "Advances my skills to a godly level.",
		SLURPERPELT = "Fashionable to say the least.",	

		SLURPER = "Aww! So furry",
		SLURPER_PELT = "Soft as it was alive.",
		ARMORSLURPER = "The grosses suit I have ever worn.",
		ORANGEAMULET = "I have invented teleportation!",
		YELLOWSTAFF = "A gem on a stick. Sometimes it's that simple.",
		YELLOWGEM = "The gem is a mellow yellow.",
		ORANGEGEM = "It is orange. And a gem. yes.",
		TELEBASE = 
		{
			VALID = "Ready at last.",
			GEMS = "Missing more purple gems.",
		},
		GEMSOCKET = 
		{
			VALID = "Good to go.",
			GEMS = "Requires a gem.",
		},
		STAFFLIGHT = "Caution should be used.",
	
        ANCIENT_ALTAR = "A master inventors table.",

        ANCIENT_ALTAR_BROKEN = "Nothing I cannot repair.",

        ANCIENT_STATUE = "Its song is calling to me.",

        LICHEN = "It has the greatest will to survive.",
		CUTLICHEN = "Edible, but non-lasting.",

		CAVE_BANANA = "It's an impossible banana.",
		CAVE_BANANA_COOKED = "Yum!",
		CAVE_BANANA_TREE = "It's an impossible tree.",
		ROCKY = "A horrific combination of rocks and claws.",
		
		COMPASS =
		{
			GENERIC="Work silly thing!",
			N = "North",
			S = "South",
			E = "East",
			W = "West",
			NE = "Northeast",
			SE = "Southeast",
			NW = "Northwest",
			SW = "Southwest",
		},

		NIGHTMARE_TIMEPIECE =
		{
			WAXING = "There's a higher concentration here!",
			STEADY = "steady...steady.",
			WANING = "It's going away.",
			DAWN = "At last, its over!",
			WARN = "Something's going on.",
			CALM = "Nothing going on. Great!",
			NOMAGIC = "No magic at all.",
		},

		HOUNDSTOOTH="Straight from its gums!",
		ARMORSNURTLESHELL="Ew! It's sticky.",
		BAT="Ack! Its going to drink my blood!",
		BATBAT = "Its a pun of itself.",
		BATWING="With enough of these maybe...",
		BATWING_COOKED="Everything is better cooked.",
		BEDROLL_FURRY="A proper bed with proper comfort.",
		BUNNYMAN="A respectable level of cute and strong.",
		FLOWER_CAVE="It glows prettily.",
		FLOWER_CAVE_DOUBLE="It glows prettily.",
		FLOWER_CAVE_TRIPLE="It glows prettily.",
		GUANO="Poop of a different kind.",
		LANTERN="A higher invention of light.",
		LIGHTBULB="It has a heavenly glow.",
		MANRABBIT_TAIL="Cut from the rump.",
		MUSHTREE_TALL  ="Its now as tall as a tree?!",
		MUSHTREE_MEDIUM="Still lively and growing.",
		MUSHTREE_SMALL ="A mush-tree?",
		RABBITHOUSE=
		{
			GENERIC = "A carrot shaped house. How remarkable.",
			BURNT = "Surprisingly flammable.",
		},
		SLURTLE="Gross slimy thing!",
		SLURTLE_SHELLPIECES="Once whole now in pieces.",
		SLURTLEHAT="Not a good alternative to gel.",
		SLURTLEHOLE="A den full of those things!",
		SLURTLESLIME="Its usefulness cannot be ignored.",
		SNURTLE="A different breed of slimy thing.",
		SPIDER_HIDER="Gah! How many types are there!",
		SPIDER_SPITTER="They spit now!",
		SPIDERHOLE="They made a nice home in the cave.",
		STALAGMITE="Pointed floor rock.",
		STALAGMITE_FULL="Pointed floor rock.",
		STALAGMITE_LOW="Pointed floor rock.",
		STALAGMITE_MED="Pointed floor rock.",
		STALAGMITE_TALL="Rocks, rocks, rocks, rocks...",
		STALAGMITE_TALL_FULL="Rocks, rocks, rocks, rocks...",
		STALAGMITE_TALL_LOW="Rocks, rocks, rocks, rocks...",
		STALAGMITE_TALL_MED="Rocks, rocks, rocks, rocks...",

		TURF_CARPETFLOOR = "Yet another ground type.",
		TURF_CHECKERFLOOR = "Yet another ground type.",
		TURF_DIRT = "Yet another ground type.",
		TURF_FOREST = "Yet another ground type.",
		TURF_GRASS = "Yet another ground type.",
		TURF_MARSH = "Yet another ground type.",
		TURF_ROAD = "Yet another ground type.",
		TURF_ROCKY = "Yet another ground type.",
		TURF_SAVANNA = "Yet another ground type.",
		TURF_WOODFLOOR = "Yet another ground type.",

		TURF_CAVE="Yet another ground type.",
		TURF_FUNGUS="Yet another ground type.",
		TURF_SINKHOLE="Yet another ground type.",
		TURF_UNDERROCK="Yet another ground type.",
		TURF_MUD="Yet another ground type.",

		TURF_DECIDUOUS = "Yet another ground type.",
		TURD_SANDY = "Yet another ground type.",
		TURF_BADLANDS = "Yet another ground type.",

		POWCAKE = "It's a lot to consume.",
        CAVE_ENTRANCE = 
        {
            GENERIC="The stone is concealing something.",
            OPEN = "A whole new world to discover.",
        },
        CAVE_EXIT = "A venture for another day.",
		MAXWELLPHONOGRAPH = "Catchy but sad.",
		BOOMERANG = "Its a deadly toy!",
		PIGGUARD = "More of a brute then its brethren.",
		ABIGAIL = "It carries a bow?",
		ADVENTURE_PORTAL = "Can it be...A way out?",
		AMULET = "Brings a small comfort.",
		ANIMAL_TRACK = "It can be food or it can be an enemy.",
		ARMORGRASS = "The easiest to make yet incredibly weak.",
		ARMORMARBLE = "Hopefully I have the muscles to carry this.",
		ARMORWOOD = "Security with imperfections.",
		ARMOR_SANITY = "Cool and mystifying.",
		ASH =
		{
			GENERIC = "Fire is always a force to be reckoned with.",
			REMAINS_GLOMMERFLOWER = "Goodbye dear Glommer!",
			REMAINS_EYE_BONE = "Goodbye dear Chester!",
			REMAINS_THINGIE = "Goodbye something...",
		},
		AXE =  "It has so many uses. Hehe",
		BABYBEEFALO = "They always start out cute.",
		BACKPACK = "More room for junk and weight for my back.",
		BACONEGGS = "Made with genius!",
		BANDAGE = "Good for injury.",
		BASALT = "A beguiling obstacle!",
		BATBAT = "A pun of itself.",
		BEARDHAIR = "It came from someone's face.",
		BEARGER = "It's deceptively passive.",
		BEARGERVEST = "A wearable trophy!",
		ICEPACK = "All you need to know is that it works.",
		BEARGER_FUR = "Lots of black and white fur.",
		BEDROLL_STRAW = "A prickly mat.",
		BEE =
		{
			GENERIC = "Nature's honey machine.",
			HELD = "There,there.",
		},
		BEEBOX =
		{
			FULLHONEY = "The bees have done their job.",
			GENERIC = "BUZZ! BUZZ!",
			NOHONEY = "No sweets.",
			SOMEHONEY = "Honey takes time.",
			BURNT = "It burned?!!",
		},
		BEEFALO =
		{
			FOLLOWER = "Yes! yes! Follow the piper.",
			GENERIC = "It's a beef-falo?!",
			NAKED = "Don't worry you'll grow it back!.",
			SLEEPING = "Shh, they're sleeping.",
		},
		BEEFALOHAT = "The beast won't know the difference.",
		BEEFALOWOOL = "There warmth is now mine.",
		BEEHAT = "To keep those dreadful stingers away.",
		BEEHIVE = "All hail queen bee!",
		BEEMINE = "Concealed inside are angry bees.",
		BEEMINE_MAXWELL = "Bottled mosquito rage!",
		BERRIES = "A wonderful snack.",
		BERRIES_COOKED = "Makes it more mushy.",
		BERRYBUSH =
		{
			BARREN = "Needs to be pooped.",
			WITHERED = "The heat is drying them up.",
			GENERIC = "A wonderful snack.",
			PICKED = "They better grow back quickly.",
		},
		BIGFOOT = "Ah, so that's where the story came from.",
		BIRDCAGE =
		{
			GENERIC = "Ready for a pet.",
			OCCUPIED = "My prisoner!",
			SLEEPING = "Awwww, he's asleep.",
		},
		BIRDTRAP = "Invented to trap birds!",
		BIRD_EGG = "Its hard exterior contains a soft interior.",
		BIRD_EGG_COOKED = "Just like breakfast back at home!",
		BISHOP = "You won't get me with your influence!",
		BLOWDART_FIRE = "I will have fire breath.",
		BLOWDART_SLEEP = "Making this was difficult.",
		BLOWDART_PIPE = "Birds can't get away this time!",
		BLUEAMULET = "Very refreshing!",
		BLUEGEM = "Cool to the touch.",
		BLUEPRINT = "Its familiarity is what I needed!",
		BELL_BLUEPRINT = "Its familiarity is what I needed!",
		BLUE_CAP = "Gooey to the touch.",
		BLUE_CAP_COOKED = "Strangely different cooked...",
		BLUE_MUSHROOM =
		{
			GENERIC = "An average mushroom.",
			INGROUND = "It does not come out at this time.",
			PICKED = "I assume it grows back?",
		},
		BOARDS = "A different shape of wood.",
		BOAT = "Perhaps I can fix it?",
		BONESHARD = "Pieces of broken bone.",
		BONESTEW = "Made by a genius!",
		BUGNET = "A bugs demise.",
		BUSHHAT = "Stealth is key.",
		BUTTER = "It.. it came from a butterfly!",
		BUTTERFLY =
		{
			GENERIC = "Dainty insect.",
			HELD = "So fragile!",
		},
		BUTTERFLYMUFFIN = "Made by a genius!",
		BUTTERFLYWINGS = "It wouldn't be so pretty without these.",
		BUZZARD = "Scavengers after my meat!",
		CACTUS = 
		{
			GENERIC = "A prickly plant.",
			PICKED = "Spiky as ever.",
		},
		CACTUS_MEAT_COOKED = "Surprisingly cookable.",
		CACTUS_MEAT = "There is a way to eat this.",
		CACTUS_FLOWER = "The prettiest flowers stem from the most dangerous roots.",

		COLDFIRE =
		{
			EMBERS = "It's slowly dying.",
			GENERIC = "I enjoy its brilliance.",
			HIGH = "The fire becoming unmanageable!",
			LOW = "The flames need to be fed.",
			NORMAL = "Tame and comforting.",
			OUT = "All things eventually go out.",
		},
		CAMPFIRE =
		{
			EMBERS = "Its brilliance is ebbing away.",
			GENERIC = "I enjoy its brilliance.",
			HIGH = "The fire becoming unmanageable!",
			LOW = "The flames need to be fed.",
			NORMAL = "Tame and comforting.",
			OUT = "All things eventually go out.",
		},
		CANE = "Good for rough terrain!",
		CATCOON = "I must have it!",
		CATCOONDEN = 
		{
			GENERIC = "Homey looking thing.",
			EMPTY = "Oh no...",
		},
		CATCOONHAT = "Its origin won't be discussed.",
		COONTAIL = "It twitches occasionally.",
		CARROT = "Eh. Good enough for me.",
		CARROT_COOKED = "Its not as grimy.",
		CARROT_PLANTED = "In its natural state.",
		CARROT_SEEDS = "Baby plant.",
		WATERMELON_SEEDS = "Baby plant.",
		CAVE_FERN = "Colorful plant.",
		CHARCOAL = "Burnt leftover from a tree.",
        CHESSJUNK1 = "A pile of broken chess pieces.",
        CHESSJUNK2 = "Another pile of broken chess pieces.",
        CHESSJUNK3 = "Even more broken chess pieces.",
		CHESTER = "Otto Von Chesterfield, Esq.",
		CHESTER_EYEBONE =
		{
			GENERIC = "The pupil is following my movements.",
			WAITING = "It closed!",
		},
		COOKEDMANDRAKE = "Its death serves a purpose.",
		COOKEDMEAT = "Broiled with care.",
		COOKEDMONSTERMEAT = "I cooked it in the hopes of a safer meal.",
		COOKEDSMALLMEAT = "Meat taste better well done!",
		COOKPOT =
		{
			COOKING_LONG = "Cooking test my patience.",
			COOKING_SHORT = "I need it now!",
			DONE = "Mmmmm! Finally ready to be devoured!",
			EMPTY = "I should fill it up! ",
			CHOPPED = "Needs to be filled.",
			BURNT = "The irony is not subtle.",
		},
		CORN = "The only plant with yellow teeth!",
		CORN_COOKED = "Needs butter!",
		CORN_SEEDS = "Baby plant.",
		CROW =
		{
			GENERIC = "Full of symbolism.",
			HELD = "It's staring at me with soulless eyes.",
		},
		CUTGRASS = "Cut grass, carries a grainy smells.",
		CUTREEDS = "Cut reeds, carries a swampy smell.",
		CUTSTONE = "Cut by a perfectionist hands.",
		DEADLYFEAST = "When food becomes dangerous.",
		DEERCLOPS = "It's..ah..oh my!!",
		DEERCLOPS_EYEBALL = "The size of my head.",
		EYEBRELLAHAT =	"Who knew an eyeball has other uses.",
		DEPLETED_GRASS =
		{
			GENERIC = "A tuft of grass.",
		},
		DEVTOOL = "Smells of cooked meat!",
		DEVTOOL_NODEV = "My strength is not of par yet.",
		DIRTPILE = "Tossed dirt?",
		DIVININGROD =
		{
			COLD = "Nothing in range.",
			GENERIC = "Its a rod of some kind.",
			HOT = "The object is close by!",
			WARM = "Something is attracting it.",
			WARMER = "The attraction grows.",
		},
		DIVININGRODBASE =
		{
			GENERIC = "It's a base to hold a greater machine.",
			READY = "Needs a key of some sort.",
			UNLOCKED = "My invention is complete!",
		},
		DIVININGRODSTART = "It is made for something!",
		DRAGONFLY = "It looks nothing like the story books!",
		ARMORDRAGONFLY = "HAHA! Invulnerable to flames!",
		DRAGON_SCALES = "Warm and razor edged.",
		DRAGONFLYCHEST = "The better to guard my treasure with!",
		LAVASPIT = 
		{
			HOT = "Lava saliva!",
			COOL = "Strange, it's turned to slimy rocks.",
		},
		DRAGONFRUIT = "It's very scaly for a fruit.",
		DRAGONFRUIT_COOKED = "Now it's scaly and delectable! .",
		DRAGONFRUIT_SEEDS = "A baby plant.",
		DRAGONPIE = "Made by a genius!",
		DRUMSTICK = "It leaves a berry aftertaste.",
		DRUMSTICK_COOKED = "It smells appetizing.",
		DUG_BERRYBUSH = "It belongs in the ground.",
		DUG_GRASS = "It belongs in the ground.",
		DUG_MARSH_BUSH = "It belongs in the ground.",
		DUG_SAPLING = "It belongs in the ground.",
		DURIAN = "It gives off a...heavy scent.",
		DURIAN_COOKED = "It's certainly smelly now!",
		DURIAN_SEEDS = "A baby plant.",
		EARMUFFSHAT = "I have bunny ears now!",
		EGGPLANT = "You can plant eggs?",
		EGGPLANT_COOKED = "It doesn't look like an omelet.",
		EGGPLANT_SEEDS = "A baby plant.",
		DECIDUOUSTREE = 
		{
			BURNING = "I wonder how long it'll burn.",
			BURNT =  "Even burnt trees have their uses.",
			POISON = "Who knew trees can frown?",
			GENERIC = "Yes, yes all leaves are accounted for.",
		},
		ACORN = 
		{
		    GENERIC = "Life begins in a shell.",
		    PLANTED = "Grow and become grand!",
		},
		ACORN_COOKED = "Quite tasty.",
		BIRCHNUTDRAKE = "The nut hides its true nature.",
		EVERGREEN =
		{
			BURNING = "I wonder how long it'll burn.",
			BURNT = "Even burnt trees have their uses.",
			CHOPPED = "No one will here you fall!",
			GENERIC = "I can see where it gets its name.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "I wonder how long it'll burn.",
			BURNT = "Even burnt trees have their uses.",
			CHOPPED = "No one will hear you fall!",
			GENERIC = "The lumpy tree is surprisingly barren.",
		},
		EYEPLANT = "The eyes are following me.",
		FARMPLOT =
		{
			GENERIC = "What an unexpected change in careers.",
			GROWING = "Go faster!",
			NEEDSFERTILIZER = "Needs to be pooped.",
			BURNT = "Why does it have to be so flammable.",
		},
		FEATHERHAT = "Now to make wings!",
		FEATHER_CROW = "Feather from a crow.",
		FEATHER_ROBIN = "Feather from a redbird.",
		FEATHER_ROBIN_WINTER = "Feather from a snowbird.",
		FEM_PUPPET = "She's trapped!",
		FIREFLIES =
		{
			GENERIC = "Their light can be put to good use!",
			HELD = "I hope they don't escape!",
		},
		FIREHOUND = "It's drooling fire.",
		FIREPIT =
		{
			EMBERS = "It's slowly dying.",
			GENERIC = "I enjoy its brilliance.",
			HIGH = "Its power is controlled!",
			LOW = "The flames must be fed.",
			NORMAL = "Tame and comforting.",
			OUT = "Like a phoenix, it will be born again.",
		},
		COLDFIREPIT =
		{
			EMBERS = "It's slowly dying.",
			GENERIC = "I enjoy its brilliance.",
			HIGH = "Its power is controlled!",
			LOW = "The flames must be fed.",
			NORMAL = "Tame and comforting.",
			OUT = "Like a pheonix, it will be born again.",
		},
		FIRESTAFF = "It creates fire. I don't know how.",
		FIRESUPPRESSOR = 
		{	
			ON = "Ice away!",
			OFF = "It's good to reserve fuel.",
			LOWFUEL = "The tank is getting empty.",
		},

		FISH = "Seafood is as good as any food.",
		FISHINGROD = "A painful waiting game.",
		FISHSTICKS = "Made by a genius!",
		FISHTACOS = "Made by a genius!",
		FISH_COOKED = "Grilled to perfection.",
		FLINT = "Its jagged and a great base for tools.",
		FLOWER = "A plant that comes in a variety of colors.",
		FLOWERHAT = "I think my self-esteem went down.",
		FLOWER_EVIL = "Hehehehe!",
		FOLIAGE = "There's a lot of green.",
		FOOTBALLHAT = "I always beat Wilson in sports.",
		FROG =
		{
			DEAD = "He wasn't meant to live.",
			GENERIC = "Awfully big!",
			SLEEPING = "He croaks in his sleep!",
		},
		FROGGLEBUNWICH = "Made by a genius!",
		FROGLEGS = "Well, I can't be picky.",
		FROGLEGS_COOKED = "Rubbery meat.",
		FRUITMEDLEY = "Made by a genius!",
		GEARS = "Ah! a small part of something grander.",
		GHOST = "That offends me as an inventor.",
		GOLDENAXE = "Gold makes a better one I guess.",
		GOLDENPICKAXE = "I don't think gold is useful here.",
		GOLDENPITCHFORK = "Fancy pitchforks makes fancy crops.",
		GOLDENSHOVEL = "Brings class to digging.",
		GOLDNUGGET = "I'll be rich whenever I come home.",
		GRASS =
		{
			BARREN = "It needs to be pooped.",
			WITHERED = "It hides from the sun.",
			BURNING = "Dry things bring fire.",
			GENERIC = " A tuft of grass.",
			PICKED = "It lived long enough.",
		},
		GREEN_CAP = "It's green like most plants.",
		GREEN_CAP_COOKED = "Strangely different now cooked...",
		GREEN_MUSHROOM =
		{
			GENERIC = "It's green like most plants!",
			GENERIC = "It's an average mushroom.",
			INGROUND = "Hiding until it's time.",
			PICKED = "It better grow back!",
		},
		GUNPOWDER = "Essential to survival in my opinion.",
		HAMBAT = "Food as a weapon... I hope I don't regret this.",
		HAMMER = "One of my favourite tools.",
		HEALINGSALVE = "Raw medication.",
		HEATROCK =
		{
			FROZEN = "It's blue and frosty.",
			COLD = "Cold to the touch.",
			GENERIC = "Sensitive temperature.",
			WARM = "Very cozy and huggable!",
			HOT = "Properly heated for the sauna!",
		},
		HOME = "Civilization?",
		HOMESIGN = 
		{
			GENERIC = "It says 'You are here'.",
			BURNT = "Now it's illegible.",
		},
		HONEY = "The food of baby bees!",
		HONEYCOMB = "Its definitely not for my hair.",
		HONEYHAM = "Made by a genius!",
		HONEYNUGGETS = "Made by a genius!",
		HORN = "I could almost hear their snorts.",
		HOUND = "Sit..stay!",
		HOUNDBONE = "Leftovers?",
		HOUNDMOUND = "What a messy home.",
		ICEBOX = "Cold is another element that bows to my will!",
		ICEHAT = "It's heavy..but it keeps me cool.",
		ICEHOUND = "There's a white one now?",
		INSANITYROCK =
		{
			ACTIVE = "It makes me laugh!",
			INACTIVE = "I'm sane now?",
		},
		JAMMYPRESERVES = "Made by a genius!",
		KABOBS = "Made by a genius!",
		KILLERBEE =
		{
			GENERIC = "Red makes it aggressive!",
			HELD = "It's trying to hurt me.",
		},
		KNIGHT = "I wonder how it works!",
		KOALEFANT_SUMMER = "This is predator versus prey!",
		KOALEFANT_WINTER = "Your meat will feed me through winter.",
		KRAMPUS = "Get your own stuff!",
		KRAMPUS_SACK = "Lets see how you like me taking your stuff.",
		LEIF = "A walking..tree..",
		LEIF_SPARSE = "A walking..tree..",
		LIGHTNING_ROD =
		{
			CHARGED = "The power is mine! Mine to control!",
			GENERIC = "Yet another element to control!",
		},
		LIGHTNINGGOAT = 
		{
			GENERIC = "I marvel at your electricity!",
			CHARGED = "It's charged?",
		},
		LIGHTNINGGOATHORN = "Lightning at my fingertips.",
		GOATMILK = "It has a more static taste!",
		LITTLE_WALRUS = "First it walks then it will attack.",
		LIVINGLOG = "Not so tough now, eh.",
		LOCKEDWES = "You're finally trapped in your own box.",
		LOG =
		{
			BURNING = "It's part fire pit!",
			GENERIC = "It once was a tree now it's wood.",
		},
		LUREPLANT = "Uuhuh..Was I drooling?",
		LUREPLANTBULB = "Time to make it work for me.",
		MALE_PUPPET = "He's trapped!",
		MANDRAKE =
		{
			DEAD = "I heard many tales of this thing.",
			GENERIC = "Is it a plant or a man?!",
			PICKED = "What do you want!",
		},
		MANDRAKESOUP = "Made by a genius!",
		MANDRAKE_COOKED = "Similar to a turnip.",
		MARBLE = "More classy than brick!",
		MARBLEPILLAR = "If I have to live here it might as well be in style.",
		MARBLETREE = "What tool do I use for this?",
		MARSH_BUSH =
		{
			BURNING = "It's not lasting long.",
			PICKED = "Ack! It pricked me!",
		},
		MARSH_PLANT = "A marshy plant.",
		MARSH_TREE =
		{
			BURNING = "Looks more threatening on fire!",
			BURNT = "Now black and menacing.",
			CHOPPED = "Its spikes could not save it!",
			GENERIC = "A very pointy tree!",
		},
		MAXWELL = "The root of all my problems.",
		MAXWELLHEAD = "Stop smiling at me!",
		MAXWELLLIGHT = "Gloomy for a light.",
		MAXWELLLOCK = "A lock in need of a key.",
		MAXWELLTHRONE = "A gritty throne for an evil king.",
		MEAT = "Meat is meat.",
		MEATBALLS = "Made by a genius!",
		MEATRACK =
		{
			DONE = "My favourite treat!",
			DRYING = "If only it was faster.",
			DRYINGINRAIN = "The rain makes it worse.",
			GENERIC = "I should make some jerky.",
			BURNT = "Fire is the consumer of all good things.",
		},
		MEAT_DRIED = "Ready by my standards.",
		MERM = "Fish out of water!",
		MERMHEAD = 
		{
			GENERIC = "Gah! The smell!",
			BURNT = "I can't breath!",
		},
		MERMHOUSE = 
		{
			GENERIC = "Horribly built.",
			BURNT = "It's better this way.",
		},
		MINERHAT = "Makes my life easier.",
		MONKEY = "Hey there little fella.",
		MONKEYBARREL = "They made barrels?",
		MONSTERLASAGNA = "Made by a genius!",
		FLOWERSALAD = "Healthier alternative.",
        ICECREAM = "I'm a glutton for icecream!",
        WATERMELONICLE = "Takes the water out of melon.",
        TRAILMIX = "A meal on the trail.",
        HOTCHILI = "Ah! Spicy!",
        GUACAMOLE = "Now I need some chips.",
		MONSTERMEAT = "The meat is purple. So not good?",
		MONSTERMEAT_DRIED = "I think it growled!",
		MOOSE = "It's powerful but lacks intelligence.",
		MOOSEEGG = "It's a giant sparking egg!",
		MOSSLING = "Did they all come out of one egg?",
		FEATHERFAN = "Now, I need a pretty thing to wave it at me.",
		GOOSE_FEATHER = "Enough fluff to fill a pillow!",
		STAFF_TORNADO = "I control the weather!!",
		MOSQUITO =
		{
			GENERIC = "My blood is too good for you!",
			HELD = "That blood better not be mine!",
		},
		MOSQUITOSACK = "It's filled up with something.",
		MOUND =
		{
			DUG = "They want to help me survive.",
			GENERIC = "Plentiful treasure to loot!",
		},
		NIGHTLIGHT = "A dark version of a nightlight.",
		NIGHTMAREFUEL = "A strange alternate fuel!",
		NIGHTSWORD = "Matches my persona!",
		NITRE = "Nit-eh? Nitr-i? Nitr... I forgot the name!",
		ONEMANBAND = "Who need other members!",
		PANDORASCHEST = "It's the curiosity that drives me.",
		PANFLUTE = "Sleep and hope not to sleep forever.",
		PAPYRUS = "Now I can write a note.",
		PENGUIN = "Where did they come from?.",
		PERD = "How dare you eat my berries!",
		PEROGIES = "Made by a genius!",
		PETALS = "I plucked its crown from its little head!",
		PETALS_EVIL = "They feel sinister.",
		PICKAXE = "There's a tool for everything.",
		PIGGYBACK = "Very smelly but more roomy.",
		PIGHEAD = 
		{	
			GENERIC = "Is it drooling?",
			BURNT = "Smells like bacon.",
		},
		PIGHOUSE =
		{
			FULL = "It's mocking me.",
			GENERIC = "How those are made I will never know.",
			LIGHTSOUT = "Let me in or I'll blow the house down!",
			BURNT = "Revenge is sweet!",
		},
		PIGKING = "Royalty at its truest form!",
		PIGMAN =
		{
			DEAD = "You will be missed.",
			FOLLOWER = "My personal body guard.",
			GENERIC = "They walk and build but don't talk.",
			GUARD = "Signs of intellect?",
			WEREPIG = "It grew fur!",
		},
		PIGSKIN = "Pink my least favourite color.",
		PIGTENT = "Ah, nestled in skin.",
		PIGTORCH = "Inviting from a distance.",
		PINECONE = 
		{
		    GENERIC = "It looks like its mother.",
		    PLANTED = "Grow so the cycle can begin again!",
		},
		PITCHFORK = "There's someone I want to prick with this.",
		PLANTMEAT = "New form of veggieburger.",
		PLANTMEAT_COOKED = "Full of vitamins and protein.",
		PLANT_NORMAL =
		{
			GENERIC = "Still in its early stage!",
			GROWING = "I wasn't meant for farming!",
			READY = "Yes! Ready for harvest.",
			WITHERED = "What a waste.",
		},
		POMEGRANATE = "One of the weirdest looking fruit.",
		POMEGRANATE_COOKED = "Haute Cuisine!",
		POMEGRANATE_SEEDS = "A baby plant.",
		POND = "I wonder what's in its depth!",
		POOP = "So it has come to this..",
		FERTILIZER = "Smelliest invention ever.",
		PUMPKIN = "I miss Halloween!",
		PUMPKINCOOKIE = "Made by a genius!",
		PUMPKIN_COOKED = "One of those mysteries.",
		PUMPKIN_LANTERN = "Festive!",
		PUMPKIN_SEEDS = "A baby plant.",
		PURPLEAMULET = "It's in my head.",
		PURPLEGEM = "I think I see something inside.",
		RABBIT =
		{
			GENERIC = "I use to have rabbits. HEHE.",
			HELD = "So soft. So scared.",
		},
		RABBITHOLE = 
		{
			GENERIC = "I will like to go down the rabbit hole.",
			SPRING = "Rabbits are getting busy down there.",
		},
		RAINOMETER = 
		{	
			GENERIC = "It replaces weathermen.",
			BURNT = "Rain cannot save it.",
		},
		RAINCOAT = "It's not red but it does its job.",
		RAINHAT = "Protection for my hair.",
		RATATOUILLE = "Made by a genius!",
		RAZOR = "I don't shave but I'll find something that will.",
		REDGEM = "Sharp and warm.",
		RED_CAP = "Red like blood.",
		RED_CAP_COOKED = "Strangely different now cooked...",
		RED_MUSHROOM =
		{
			GENERIC = "An average mushroom.",
			INGROUND = "Not its time yet.",
			PICKED = "It better grow back!",
		},
		REEDS =
		{
			BURNING = "Fire likes it!",
			GENERIC = "It sways in the wind.",
			PICKED = "Not much left.",
		},
        RELIC = 
        {
            GENERIC = "It's a relic because it's ancient.",
            BROKEN = "Broken by the past.",
        },
        RUINS_RUBBLE = "Nothing I can't repair.",
        RUBBLE = "Rock babies.",
		RESEARCHLAB = 
		{	
			GENERIC = "A basic level invention.",
			BURNT = "Basic things never last.",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "More advanced in its tech!",
			BURNT = "My love didn't make it last.",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "It radiates illogical and darkness.",
			BURNT = "Magic is not fireproof.",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "My invention questions reality.",
			BURNT = "Fire logic defies everything else.",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "Looks like my rival Wilson!",
			BURNT = "Poor Wilson didn't last.",
		},
		RESURRECTIONSTONE = "Witch-craft of some sort?",
		ROBIN =
		{
			GENERIC = "Where's batman, Robin?",
			HELD = "Docile for a wild bird.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "The color blue means you're ready for winter.",
			HELD = "Incredibly cuddly!",
		},
		ROBOT_PUPPET = "It's trapped!",
		ROCK_LIGHT =
		{
			GENERIC = "Dried lava.",
			OUT = "Seems delicate.",
			LOW = "It appears to be hardening.",
			NORMAL = "At a comfortable level.",
		},
		ROCK = "Too big to be of any use.",
		ROCK_ICE = 
		{
			GENERIC = "Clustered ice.",
			MELTED = "Just a puddle at the moment.",
		},
		ROCK_ICE_MELTED = "Just a puddle at the moment.",
		ICE = "Frozen water that needs to be cubed.",
		ROCKS = "The most primal tool.",
        ROOK = "If I can make it work for me!",
		ROPE = "To tie things with.",
		ROTTENEGG = "It certainly isn't fresh!",
		SANITYROCK =
		{
			ACTIVE = "AHH! My mind!",
			INACTIVE = "It's gone?",
		},
		SAPLING =
		{
			BURNING = "It's slowly being consumed!",
			WITHERED = "Looks dried up.",
			GENERIC = "So young and ignorant!",
			PICKED = "Ignorance doesn't last.",
		},
		SEEDS = "Mystery plant baby.",
		SEEDS_COOKED = "If I listen I can hear their little cries.",
		SEWING_KIT = "If only I had my mother!",
		SHOVEL = "The earth has many secrets.",
		SILK = "Fine clothes are made from these.",
		SKELETON = "I guess he starved.",
		SKELETON_PLAYER = "Is...Is..Is that?!",
		SKULLCHEST = "The skull makes it less compelling.",
		SMALLBIRD =
		{
			GENERIC = "Its eye is the size of its body.",
			HUNGRY = "Hungry are ya!",
			STARVING = "Little bird. Don't starve.",
		},
		SMALLMEAT = "Small animal. Small meat",
		SMALLMEAT_DRIED = "Not-Big jerky.",
		SPEAR = "Vintage weapon.",
		SPIDER =
		{
			DEAD = "The leg twitched!",
			GENERIC = "They're cute in a cage.",
			SLEEPING = "They're not bad when they're not attacking.",
		},
		SPIDERDEN = "What's it like in there?",
		SPIDEREGGSACK = "Their tiny lives are at he palm of my hands.",
		SPIDERGLAND = "It has medicinal use..I think.",
		SPIDERHAT = "I defeated the queen and now I wear her head to be king!",
		SPIDERQUEEN = "AHHHHHHHHH!",
		SPIDER_WARRIOR =
		{
			DEAD = "I like you better dead!",
			GENERIC = "It's the bully of all spiders.",
			SLEEPING = "I'm tempted to step on it.",
		},
		SPOILED_FOOD = "The hair is proof of spoilage.",
		STATUEHARP = "Somebody doesn't love love.",
		STATUEMAXWELL = "The sight of him disgust me.",
		STINGER = "A natural weapon!",
		STRAWHAT = "Decent headware.",
		STUFFEDEGGPLANT = "Made by a genius!",
		SUNKBOAT = "I wonder if there's a way to pull it in!",
		SWEATERVEST = "Dapper and cozy.",
		REFLECTIVEVEST = "Scares the sun away!",
		HAWAIIANSHIRT = "More for vacation use.",
		TAFFY = "Made by genius!",
		TALLBIRD = "Um, Big bird?!",
		TALLBIRDEGG = "To eat or not to eat?",
		TALLBIRDEGG_COOKED = "Its size makes it better.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Cccold!",
			GENERIC = "Break free little bird!",
			HOT = "The egg is turning red..and sweating?",
			LONG = "Having a baby takes forever...",
			SHORT = "Almost time for it to be born.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "The egg is huge!",
			PICKED = "Barren as my plate.",
		},
		TEENBIRD =
		{
			GENERIC = "Pfft. Teenagers",
			HUNGRY = "Go get food!",
			STARVING = "Why are you looking at me that way?!",
		},
		TELEBASE =
		{
			VALID = "Powered and ready.",
			GEMS = "Needs more gems. Preferably purple.",
		},
		GEMSOCKET = 
		{
			VALID = "Ready.",
			GEMS = "Needs a gem.",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "Never has travelling through space and time been so surreal!",
			GENERIC = "An opening to something new!",
			LOCKED = "Something is not right.",
			PARTIAL = "Soon, my invention will be complete!",
		},
		TELEPORTATO_BOX = "This box holds the secret of the universe.",
		TELEPORTATO_CRANK = "The switch to ultimate power.",
		TELEPORTATO_POTATO = "It may look like a potato but...It's not!",
		TELEPORTATO_RING = "A multidimensional ring.",
		TELESTAFF = "Everything is now open to me.",
		TENT = 
		{
			GENERIC = "The most suitable shelter.",
			BURNT = "My home!",
		},
		SIESTAHUT = 
		{
			GENERIC = "A safe place to nap away from heat.",
			BURNT = "Heat finally overcame it.",
		},
		TENTACLE = "I should be cautious were I step.",
		TENTACLESPIKE = "It's stiff now.",
		TENTACLESPOTS = "When did it have spots?",
		TENTACLE_PILLAR = "Bigger than the surface ones.",
		TENTACLE_PILLAR_ARM = "It has offspring!",
		TENTACLE_GARDEN = "More of them!",
		TOPHAT = "Made entirely for me.",
		TORCH = "Basic tool of light.",
		TRANSISTOR = "I like how it purrs.",
		TRAP = "Secure and ready for use.",
		TRAP_TEETH = "It will leave a nasty bite.",
		TRAP_TEETH_MAXWELL = "Hmph! HE thinks I will fall for that!",
		TREASURECHEST = 
		{
			GENERIC = "Yay! Treasure!",
			BURNT = "Noo! Why?!.",
		},
		TREASURECHEST_TRAP = "Not surprising!",
		TREECLUMP = "As if it was purposely put there.",
		TRINKET_1 = "They're melted as one.",
		TRINKET_10 = "Not very sanitary.",
		TRINKET_11 = "What? What did you say?",
		TRINKET_12 = "The use was leached out of it.",
		TRINKET_2 = "Not worth the money spent.",
		TRINKET_3 = "Impossible to loosen.",
		TRINKET_4 = "The warrior once defended gardens.",
		TRINKET_5 = "Maybe if I build a bigger replica.",
		TRINKET_6 = "They remind me of happier days.",
		TRINKET_7 = "A toy from childhood!",
		TRINKET_8 = "If there is a tub somewhere I'm in.",
		TRINKET_9 = "Complete junk.",
		TRUNKVEST_SUMMER = "More prepared for the wild.",
		TRUNKVEST_WINTER = "For winter comfort.",
		TRUNK_COOKED = "I cooked the boogers away.",
		TRUNK_SUMMER = "He can't smell the summer air any more.",
		TRUNK_WINTER = "He can't smell the chilly air now.",
		TUMBLEWEED = "It's a tumbling junk collector.",
		TURF_CARPETFLOOR = "Not as soft as I wanted it.",
		TURF_CHECKERFLOOR = "Fits my style.",
		TURF_DIRT = "A chunk of ground.",
		TURF_FOREST = "A chunk of ground.",
		TURF_GRASS = "A chunk of ground.",
		TURF_MARSH = "A chunk of ground.",
		TURF_ROAD = "Hastily cobbled stones.",
		TURF_ROCKY = "A chunk of ground.",
		TURF_SAVANNA = "A chunk of ground.",
		TURF_WOODFLOOR = "These are floorboards.",
		TURKEYDINNER = "Mmmm.",
		TWIGS = "A collection of branches.",
		UMBRELLA = "Better equipped for rain.",
		GRASS_UMBRELLA = "The rain leaks a little.",
		UNIMPLEMENTED = "It doesn't look finished! It could be dangerous.",
		WAFFLES = "Made by a genius!",
		WALL_HAY = 
		{	
			GENERIC = "I feel a little protected.",
			BURNT = "Should have known better.",
		},
		WALL_HAY_ITEM = "Not practical.",
		WALL_STONE = "I feel more guarded now.",
		WALL_STONE_ITEM = "Part of my castle.",
		WALL_RUINS = "Crumbled castle.",
		WALL_RUINS_ITEM = "A history in its prime.",
		WALL_WOOD = 
		{
			GENERIC = "Classic!",
			BURNT = "Disappeared in history!",
		},
		WALL_WOOD_ITEM = "Doesn't cover much.",
		WALRUS = "Fancy for a beast.",
		WALRUSHAT = "Well made for me",
		WALRUS_CAMP =
		{
			EMPTY = "Marked for camping.",
			GENERIC = "It looks warm for a frozen home.",
		},
		WALRUS_TUSK = "It's a trophy for now.",
		WARG = "Don't you snap at me!",
		WASPHIVE = "Such furiousness.",
		WATERMELON = "It's a messy fruit.",
		WATERMELON_COOKED = "More messy and juicy.",
		WATERMELONHAT = "The more I wear it the stickier I am.",
		WETGOOP = "Made by.. not me!",
		WINTERHAT = "It'll keep my head warm and in season.",
		WINTEROMETER = 
		{
			GENERIC = "I am the best inventor.",
			BURNT = "The best cannot predict everything.",
		},
		WORMHOLE =
		{
			GENERIC = "It quivers at my presence.",
			OPEN = "My instinct tells me its okay.",
		},
		WORMHOLE_LIMITED = "Is it possible for it to get sick?",
		ACCOMPLISHMENT_SHRINE = "The world must know of Wezla!",        
		LIVINGTREE = "I'm feeling a little threatened.",
		ICESTAFF = "I need mittens to hold this.",
	},
	DESCRIBE_GENERIC = "You tell me what it is.",
	DESCRIBE_TOODARK = "Everything went black!",
	DESCRIBE_SMOLDERING = "Wezla saves the day again.",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "Mmm not to early not to late.",
	},
}
